language: python
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27-django18
  - python: "3.2"
    env: TOX_ENV=py32-django18
  - python: "3.3"
    env: TOX_ENV=py33-django18
  - python: "3.4"
    env: TOX_ENV=py34-django18
  - python: "3.5"
    env: TOX_ENV=py35-django18

  - python: "2.7"
    env: TOX_ENV=py27-django19
  - python: "3.4"
    env: TOX_ENV=py34-django19
  - python: "3.5"
    env: TOX_ENV=py35-django19

  - python: "2.7"
    env: TOX_ENV=py27-django110
  - python: "3.4"
    env: TOX_ENV=py34-django110
  - python: "3.5"
    env: TOX_ENV=py35-django110

  - python: "2.7"
    env: TOX_ENV=py27-django111
  - python: "3.4"
    env: TOX_ENV=py34-django111
  - python: "3.5"
    env: TOX_ENV=py35-django111
  - python: "3.6"
    env: TOX_ENV=py36-django111

  - python: "3.4"
    env: TOX_ENV=py34-django20
  - python: "3.5"
    env: TOX_ENV=py35-django20
  - python: "3.6"
    env: TOX_ENV=py36-django20
  - python: "3.7-dev"
    env: TOX_ENV=py37-django20

  - python: "3.5"
    env: TOX_ENV=py35-django21
  - python: "3.6"
    env: TOX_ENV=py36-django21
  - python: "3.7-dev"
    env: TOX_ENV=py37-django21
install:
- pip install tox
- if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install virtualenv==13.1.2; fi
script:
- tox -e $TOX_ENV
