# Generated by Django 3.0 on 2020-01-08 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_auto_20191229_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date&time this question was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date&time this question was updated. Automatically generated when the model updates.')),
                ('content', models.TextField(default='Write the content of your question here.')),
                ('author', models.ForeignKey(help_text='The user that posted this question.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date&time this question was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date&time this question was updated. Automatically generated when the model updates.')),
                ('points', models.IntegerField(default=10, help_text='number of points given for getting the correct answer to this question')),
                ('content', models.TextField(default='Write the content of your question here.')),
                ('correct', models.BooleanField(default=False, help_text='Is this the correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Question')),
            ],
        ),
    ]
