# Generated by Django 3.0 on 2019-12-30 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Exam Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default='Exam Name', on_delete=django.db.models.deletion.CASCADE, to='trivia.Exam'),
        ),
    ]
