# Generated by Django 3.0 on 2020-01-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20200108_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.TextField(default='Write the content of your question here.', max_length=200),
        ),
    ]
