# Generated by Django 3.0 on 2020-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20200108_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False, help_text='Is this the multiple choice answer'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.CharField(default='Write the content of your question here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='Write the content of your question here.', max_length=200),
        ),
    ]
