# Generated by Django 3.0 on 2020-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20200109_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False, help_text='Is this a multiple choice answer'),
        ),
    ]
