# Generated by Django 3.0 on 2019-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default='Write the content of your page here.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='Title of your page.', max_length=600, unique=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
